disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Casa de JuJu"

[params]
  displayName = "English 🇬🇧"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/rev.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Another JuJu Production"
  # copyright = "Another JuJu Production"

[params.author]
   name = "Julian Darío Gutierrez"
   email = "mail@juju.casa"
   image = "img/juju3.jpg"
   imageQuality = 100
   headline = "<br>From 🇨🇴 ~ Lives in 🇳🇴 <br> NeoAboriginal 🦊 <br> Kambo practitioner 🐸"
   bio = "From 🇨🇴 ~ Lives in 🇳🇴 <br> NeoAboriginal 🦊 <br> Kambo practitioner 🐸"
   links = [
     { email = "mailto:mail@juju.casa" },
     { spotify = "https://open.spotify.com/user/jujudario" },
     { instagram = "https://instagram.com/neoaboriginal" },
     { rss = "https://juju.casa/index.xml" },
 ]
