disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Casa de JuJu"

[params]
  displayName = "English 🇬🇧"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/rev.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Another JuJu Production"
  # copyright = "Another JuJu Production"

[params.author]
   name = "JuJu Darío"
   email = "mail@juju.casa"
   image = "img/Ghiblied.jpg"
   imageQuality = 96
   headline = ""
   bio = "NeoAboriginal 🦊 <br> Kambo practitioner 🐸 <br> Amplifier of truth 💎 <br> Agorism and decentralization 🌐"
   links = [
     { rss = "https://juju.casa/index.xml" },
     { email = "mailto:mail@juju.casa" },
     { spotify = "https://open.spotify.com/user/jujudario" },
     { instagram = "https://instagram.com/neoaboriginal" },
 ]
