# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Categories 🗃️"
#  pageRef = "category"
#  weight = 10

#[[main]]
#  name = "Notes 📝"
#  parent = "Categories 🗃️"
#  pageRef = "note"
#  weight = 10

#[[main]]
#  name = "Photos 📸"
#  parent = "Categories 🗃️"
#  pageRef = "photo"
#  weight = 20

#[[main]]
#  name = "Bookmarks 🔖"
#  parent = "Categories 🗃️"
#  pageRef = "bookmark"
#  weight = 30

#[[main]]
#  name = "Quotes 🗣️"
#  parent = "Categories 🗃️"
#  pageRef = "quote"
#  weight = 40

#[[main]]
#  name = "Videos 📽️"
#  parent = "Categories 🗃️"
#  pageRef = "video"
#  weight = 50

#[[main]]
#  name = "Likes ❤️"
#  parent = "Categories 🗃️"
#  pageRef = "like"
#  weight = 60

#[[main]]
#  name = "RePosts 🔁"
#  parent = "Categories 🗃️"
#  pageRef= "repost"
#  weight = 70

#[[main]]
#   name = "Tags 🏷️"
#   pageRef = "tags"
#   weight = 20

#[[main]]
#  name = "Podcasts 🎙️"
#  parent = "Categories 🗃️"
# url = "https://open.spotify.com/playlist/2zVbDT1D2MJFRNU6Po2blC?si=d9a65f0280ed4a49"
#  weight = 80

#[[main]]
#  name = "Checkins 📍"
#  parent = "Stream ⚡"
#  pageRef = "checkin"
#  weight = 40

[[main]]
  name = "Kambo 🐸"
  url = "https://kam.bo"
  weight = 30

[[main]]
  name = "About 🧔🏻‍♂️"
  url = "/about"
  weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags 🏷️"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories 🗃️"
   pageRef = "category"
   weight = 20